<?php


 ?>
 <title><?Php client_name ?></title>
 <meta charset="utf-8" <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="view/css/bootstrap.min.css">
 <link rel="stylesheet" href="view/css/w3.css">
 <script src="view/js/jquery.min.js"></script>
 <script src="view/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
 <link href="https://fonts.googleapis.com/css?family=Sacramento" rel="stylesheet">
 <script src="view/js/simple.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
 <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
 <link rel="stylesheet" href="view/css/simple.css">
